name: CI

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Before checkout
        run: |
          pwd
          ls -la

      - uses: actions/checkout@v4

      - name: After checkout
        run: |
          pwd
          ls -la
